port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
proxies: null
proxy-groups:
  - name: AUTOPROXY
    type: url-test
    use:
      - best server
      - server1
      - server2
      - server3
      - server4
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: MANUALPROXY
    type: select
    use:
      - best server
      - server1
      - server2
      - server3
      - server4
    proxies:
      - "AUTOPROXY"

proxy-providers:
  best server:
    type: http
    url: https://cdn.jsdelivr.net/gh/Ak1kAZE/ClashRule@main/Rule_immtel.yml
    path: ./proxy/Rule_immtel.yaml
    interval: 86400
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204
  server1:
    type: http
#    url: https://cdn.jsdelivr.net/gh/zjr13808836946/zjr_clash@main/v2ray_t_clash
    url: https://naixisubs.com/downloadConfig/Clash.aspx?t=trojan&eq=windows&urk=a53b0386-265b-4490-8e0b-9016f9145c14
    path: ./proxy/server1.yaml
    interval: 7200
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204
  server2:
    type: http
    url: https://cdn.jsdelivr.net/gh/colatiger/v2ray-nodes@master/clash.yaml
    path: ./proxy/server2.yaml
    interval: 7200
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204
  server3:
    type: http
    url: https://gfwglass.tk/clash/proxies?c=HK,TW,KR
    path: ./proxy/server3.yaml
    interval: 7200
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204
  server4:
    type: http
    url: http://8.135.91.61/clash/proxies?c=HK,KR,TW,SG
    path: ./proxy/server4.yaml
    interval: 7200
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204

rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 86400
  Global:
    type: http
    behavior: classical
    path: ./ruleset/Global.yaml
    url: https://cdn.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Proxy.yaml
    interval: 86400
  China:
    type: http
    behavior: classical
    path: ./ruleset/China.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/China.yaml
    interval: 86400
rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,China,DIRECT
  - RULE-SET,tld-not-cn,MANUALPROXY
  - RULE-SET,proxy,MANUALPROXY
  - RULE-SET,Global,MANUALPROXY
  - RULE-SET,telegramcidr,MANUALPROXY
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT